#### Aliases
aliases = []

#### Dependencies
dependencies = []

#### Specification Link
spec = "https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details"

#### License
license = "MIT"

#### Browser compatibility
[browsers]
android = "<4"
bb = "*"
chrome = "<12"
edge = "<79"
edge_mob = "<79"
firefox = "<49"
ios_chr = "*"
ios_saf = "<6"
ie = "*"
ie_mob = "*"
opera = "<15"
op_mini = "*"
safari = "<6"
firefox_mob = "<49"
samsung_mob = "<4"

[install]
module = "details-element-polyfill"
paths = [ "dist/details-element-polyfill.js" ]